name = "cogallery-media-proxy"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[env.production]

[env.production.vars]
BUCKET_NAME = "cogallery-media"

[[env.production.r2_buckets]]
binding = "COGALLERY_MEDIA"
bucket_name = "cogallery-photos"