version: '3.8'

services:
  seedbox:
    build: .
    restart: always
    environment:
      - APP_URL=${APP_URL}
      - BOT_EMAIL=${BOT_EMAIL}
      - BOT_PASSWORD=${BOT_PASSWORD}
    volumes:
      # This volume persists the Puppeteer IndexedDB cache across restarts!
      # It ensures the bot doesn't lose downloaded files if the server restarts.
      - seedbox-data:/app/bot-data

volumes:
  seedbox-data:
