import nodeDataChannel from 'node-datachannel'
import { getFile } from './fileStore.js'

const ICE_SERVERS = [
  'stun:stun.l.google.com:19302',
  'stun:stun1.l.google.com:19302',
  'stun:stun2.l.google.com:19302',
]

// Initialize the node-datachannel library logging (optional, can be quiet)
// nodeDataChannel.initLogger('Fatal')

/**
 * Handles an incoming file request from a leecher by spinning up a PeerConnection
 * and streaming the file from disk to the DataChannel.
 */
export async function handleFileRequest(payload, channel, activePeers) {
  const { requesterId, photoId, offerId } = payload
  
  // Get file from disk cache
  const cached = await getFile(photoId)
  if (!cached) return

  console.log(`[WebRTC] Seeding file ${photoId} to user ${requesterId.slice(0,6)}...`)

  const pc = new nodeDataChannel.PeerConnection(offerId, { iceServers: ICE_SERVERS })
  activePeers.set(offerId, pc)

  const dc = pc.createDataChannel(`file:${photoId}`, { ordered: true })
  
  dc.onOpen(() => {
    // Send metadata first
    dc.sendMessage(JSON.stringify({
      type: 'meta',
      filename: cached.filename,
      mimeType: cached.mimeType,
      size: cached.size,
    }))

    const MAX_CHUNK_SIZE = 64 * 1024 // 64KB
    const LOW_THRESHOLD = 2 * 1024 * 1024 // 2MB

    let offset = 0
    const total = cached.size
    
    // Convert Buffer to ArrayBuffer/Uint8Array for node-datachannel
    const buffer = cached.buffer

    const sendNextChunk = () => {
      try {
        while (offset < total) {
          // Check buffered amount for back-pressure
          if (dc.bufferedAmount() > LOW_THRESHOLD) {
            return // wait for bufferedAmountLow
          }
          const end = Math.min(offset + MAX_CHUNK_SIZE, total)
          dc.sendMessageBinary(buffer.subarray(offset, end))
          offset = end
        }
        
        if (offset >= total) {
          dc.sendMessage(JSON.stringify({ type: 'done' }))
          console.log(`[WebRTC] Finished sending ${photoId} to ${requesterId.slice(0,6)}`)
        }
      } catch (err) {
        console.error(`[WebRTC] Error sending chunks:`, err)
      }
    }

    // Set callback for back-pressure draining
    dc.onBufferedAmountLow(() => {
      sendNextChunk()
    })

    // Start sending
    sendNextChunk()
  })

  // Handle ICE candidates generated by our local node
  pc.onLocalCandidate((candidate, mid) => {
    // Note: node-datachannel passes candidate as string and mid as string
    channel.send({
      type: 'broadcast',
      event: 'ice-candidate',
      payload: { 
        targetId: requesterId, 
        offerId, 
        candidate: { candidate, sdpMid: mid, sdpMLineIndex: 0 } 
      },
    })
  })

  // Handle local SDP description generation
  pc.onLocalDescription((sdp, type) => {
    channel.send({
      type: 'broadcast',
      event: 'offer',
      payload: { targetId: requesterId, offerId, sdp },
    })
  })

  // Start the connection process (creating the offer implicitly triggers onLocalDescription)
}

/**
 * Initiates a request to download a file from other peers in the swarm.
 */
export function requestFile(eventId, photoId, userId, targetUploaderId, channel, activePeers, onFileReceived) {
  return new Promise((resolve) => {
    const offerId = `${userId}-${Date.now()}-${Math.random().toString(36).slice(2)}`
    let resolved = false
    
    const timer = setTimeout(() => {
      if (!resolved) {
        const pc = activePeers.get(offerId)
        if (pc) pc.close()
        activePeers.delete(offerId)
        resolve(null)
      }
    }, 60000)

    const pc = new nodeDataChannel.PeerConnection(offerId, { iceServers: ICE_SERVERS })
    activePeers.set(offerId, pc)
    
    // We expect the remote peer to create the DataChannel because they sent the offer
    pc.onDataChannel((dc) => {
      let filename = 'download'
      let mimeType = 'application/octet-stream'
      let expectedSize = 0
      const chunks = []

      dc.onMessage((msg) => {
        if (typeof msg === 'string') {
          try {
            const parsed = JSON.parse(msg)
            if (parsed.type === 'meta') {
              filename = parsed.filename
              mimeType = parsed.mimeType
              expectedSize = parsed.size
            } else if (parsed.type === 'done') {
              // Reconstruct full buffer from chunks
              const buffer = Buffer.concat(chunks)
              clearTimeout(timer)
              resolved = true
              pc.close()
              activePeers.delete(offerId)
              
              if (onFileReceived) {
                onFileReceived(photoId, buffer, filename, mimeType)
              }
              resolve({ buffer, filename, mimeType })
            }
          } catch { /* ignore */ }
        } else {
          // Binary chunk
          chunks.push(msg) // node-datachannel passes Buffer
        }
      })
    })

    pc.onLocalCandidate((candidate, mid) => {
      channel.send({
        type: 'broadcast',
        event: 'ice-candidate',
        payload: { targetId: targetUploaderId, offerId, candidate: { candidate, sdpMid: mid, sdpMLineIndex: 0 } },
      })
    })

    pc.onLocalDescription((sdp, type) => {
      channel.send({
        type: 'broadcast',
        event: 'answer',
        payload: { offerId, sdp },
      })
    })

    // Give time for channel to establish
    setTimeout(() => {
      channel.send({
        type: 'broadcast',
        event: 'file-request',
        payload: { requesterId: userId, photoId, offerId },
      })
    }, 500)
  })
}
